server:
  port: ${PORT:8080}
spring: 
  h2: 
    console:
      enabled: true
      path: /h2-console
      
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://ec2-18-207-52-108.compute-1.amazonaws.com/postgres
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver