server:
  port: ${PORT:8080}
spring: 
  application:
    name: demo-rest-service 
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
